name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-sdk:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - id: cache
      uses: actions/cache@v1
      with:
        path: .devcontainer
        key: ${{ runner.os }}-cache-sdk-${{ hashFiles('.devcontainer/Dockerfile') }}
    - name: Create SDK
      if: steps.cache.outputs.cache-hit != 'true'
      uses: docker/build-push-action@v1
      with:
          username: juselius
          password: ${{ secrets.DOCKER_HUB }}
          repository: juselius/inf-3910-webapp-sdk
          path: .devcontainer
          tags: latest

  build-release:
    container: juselius/inf-3910-webapp-sdk:latest
    env:
      target: release
    runs-on: self-hosted
    needs: create-sdk
    steps:
    - uses: actions/checkout@v2
    - name: Restore NuGet
      uses: actions/cache@v1
      with:
        path: ~/.nuget
        key: ${{ runner.os }}-cache-nuget-${{ hashFiles('**/paket.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-nuget-
    - name: Restore npm
      uses: actions/cache@v1
      with:
        path: ./node_modules
        key: ${{ runner.os }}-cache-npm-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-npm-
    - name: Install dependencies
      run: |
        dotnet tool restore
        yarn install
        paket install
    - name: Build
      run: |
        fake build -t ${{ env.target }}
    - name: Release
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}/${{ env.target }}
        registry: docker.pkg.github.com
        tags: latest
        tag_with_ref: true
        tag_with_sha: true

  tests:
    container: juselius/inf-3910-webapp-sdk:latest
    runs-on: self-hosted
    needs: create-sdk
    steps:
    - uses: actions/checkout@v2
    - name: Restore NuGet
      uses: actions/cache@v1
      with:
        path: ~/.nuget
        key: ${{ runner.os }}-cache-nuget-${{ hashFiles('**/paket.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-nuget-
    - name: Restore npm
      uses: actions/cache@v1
      with:
        path: ./node_modules
        key: ${{ runner.os }}-cache-npm-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-npm-
    - name: Install dependencies
      run: |
        dotnet tool restore
        yarn install
        paket install
    - name: Run unit tests
      run: dotnet run -p Tests
    - name: Run UI tests
      run: dotnet run -p Tests -- --canopy headless
