name: Create SDK

on:
  push:
    branches: [ master ]
    paths:
    - .devcontainer/Dockerfile
  pull_request:
    branches: [ master ]

jobs:
  create-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create SDK
      uses: docker/build-push-action@v1
      with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}/sdk
          registry: docker.pkg.github.com
          path: .devcontainer
          tags: latest